"""
JWT Authentication module for FastAPI.
Validates JWT tokens generated by the Node.js backend.
"""
from typing import Optional
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
import jwt

from app.config import settings


# HTTP Bearer token scheme
security = HTTPBearer(auto_error=False)


class TokenPayload:
    """Parsed JWT token payload."""
    def __init__(self, user_id: str, email: str, name: Optional[str] = None):
        self.user_id = user_id
        self.email = email
        self.name = name


def decode_jwt(token: str) -> dict:
    """
    Decode and validate a JWT token.
    
    Args:
        token: The JWT token string
        
    Returns:
        Decoded token payload
        
    Raises:
        HTTPException if token is invalid or expired
    """
    try:
        payload = jwt.decode(
            token,
            settings.JWT_SECRET,
            algorithms=[settings.JWT_ALGORITHM]
        )
        return payload
    except jwt.ExpiredSignatureError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token has expired",
            headers={"WWW-Authenticate": "Bearer"},
        )
    except jwt.InvalidTokenError as e:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Invalid token: {str(e)}",
            headers={"WWW-Authenticate": "Bearer"},
        )


async def get_current_user(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security)
) -> TokenPayload:
    """
    Dependency to get the current authenticated user from JWT token.
    
    Usage:
        @app.get("/protected")
        async def protected_route(user: TokenPayload = Depends(get_current_user)):
            return {"user_id": user.user_id, "email": user.email}
    """
    if credentials is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authenticated",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    payload = decode_jwt(credentials.credentials)
    
    # Extract user info from token (Node.js token structure)
    user_id = payload.get("userId") or payload.get("sub") or payload.get("id")
    email = payload.get("email", "")
    name = payload.get("name")
    
    if not user_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token payload - missing user ID",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    return TokenPayload(user_id=user_id, email=email, name=name)


async def get_optional_user(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security)
) -> Optional[TokenPayload]:
    """
    Dependency for optional authentication.
    Returns None if no valid token provided, otherwise returns user.
    
    Usage:
        @app.get("/public-or-private")
        async def route(user: Optional[TokenPayload] = Depends(get_optional_user)):
            if user:
                return {"message": f"Hello {user.email}"}
            return {"message": "Hello anonymous"}
    """
    if credentials is None:
        return None
    
    try:
        payload = decode_jwt(credentials.credentials)
        user_id = payload.get("userId") or payload.get("sub") or payload.get("id")
        email = payload.get("email", "")
        name = payload.get("name")
        
        if user_id:
            return TokenPayload(user_id=user_id, email=email, name=name)
        return None
    except HTTPException:
        return None
